<a href="https://colab.research.google.com/github/toot09/15012020_made/blob/master/Numpy%EC%9D%98%20%EA%B8%B0%EB%B3%B8%20%EC%97%B0%EC%82%B0%20%5B%20Python%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B3%BC%20%EC%9D%B4%EB%AF%B8%EC%A7%80%20%EC%B2%98%EB%A6%AC%20%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# 행렬 더하기
#array1 = np.random.normal(0,1,(2,3))
array1 = np.random.randint(0,10, size=8).reshape(4,2)
print(array1)
print(array1*2)

In [10]:
#size가 다른 행렬들의 덧셈(broadcast)
#한개는 행,열 size가 1이어야함. ex) np.arange(3).reshape(1,3) or np.arange(3).reshape(3,1)
array1 = np.arange(4).reshape(2,2)
print(array1)
array2 = np.arange(2).reshape(1,2)
print(array2)
print(np.add(array1,array2))
print("=============")
array3 = np.arange(4).reshape(2,2)
print(array3)
array4 = np.arange(2).reshape(2,1)
print(array4)
print(np.add(array3,array4))
print("=============")
# 행, 열 둘중에 하나라도 맞아야 덧셈이 가능함
#array5 = np.arange(9).reshape(3,3)
#print(array5)
#array6 = np.arange(2).reshape(2,1)
#print(array6)
#print(np.add(array5,array6))

[[0 1]
 [2 3]]
[[0 1]]
[[0 2]
 [2 4]]
[[0 1]
 [2 3]]
[[0]
 [1]]
[[0 1]
 [3 4]]


In [47]:
# MASKING (마스킹)
array1 = np.arange(9).reshape(3,3)

array2 = array1 < 5
print(array2)

# 마스킹 배열의 True 값만 handling 할 수 있다.!
# 원소 일일히 if문 쓰지않고 바로 체크할 수 있어서 좋다
array1[array2] = 100
print(array1)

arrayTF = (array1 % 2 == 1)
array1[arrayTF] = 23
print(array1)

[[ True  True  True]
 [ True  True False]
 [False False False]]
[[100 100 100]
 [100 100   5]
 [  6   7   8]]
[[100 100 100]
 [100 100  23]
 [  6  23   8]]


In [56]:
array1 = np.arange(16).reshape(4,4)
print(array1)
print("최대값 : ",np.max(array1))
print("최소값 : ",np.min(array1))
print("합계값 : ",np.sum(array1))
print("평균값 : ",np.mean(array1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
최대값 :  15
최소값 :  0
합계값 :  120
평균값 :  7.5


In [64]:
array1 = np.arange(16).reshape(4,4)
print(array1)
left, right = np.split(array1, [1], axis=0)
#ex2 = np.split(array1, [1], axis=1)
print(left)
print(right)
print("=====================")
#행을 쪼개서 sum
print(np.sum(array1,axis = 0))
print("=====================")
#열을 쪼개서 sum
print(np.sum(array1,axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 28 32 36]
[ 6 22 38 54]
