<a href="https://colab.research.google.com/github/toot09/15012020_made/blob/master/Numpy%EC%9D%98_%EA%B8%B0%EB%B3%B8_%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

list_data = [1,2,3,4]
print(list_data)
array = np.array(list_data)
print(array)
print(array.dtype)
print(array.size)

[1, 2, 3, 4]
[1 2 3 4]
int64
4


In [24]:
# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

# 0행렬
array2 = np.zeros((4,4),dtype=float)
print(array2)

# 1행렬
array3 = np.ones((3,2),dtype=str)
print(array3)

# 0~9 랜덤 초기화
array4 = np.random.random_integers(0,10,(5,5))
print(array4)

# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열(표준정규분포)
array5 = np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1']
 ['1' '1']
 ['1' '1']]
[[ 7  1  1 10 10]
 [10  7  1  5  2]
 [ 3  3  8  1  3]
 [ 7  8  0 10  9]
 [ 8  0  2  0  5]]
[[ 0.67902574 -0.69289511  0.44224974]
 [-0.6416598   0.02155819  0.12803804]
 [ 0.66912475  0.1317138   0.4335487 ]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  del sys.path[0]
