<a href="https://colab.research.google.com/github/toot09/15012020_made/blob/master/Numpy%EC%9D%98%20%EA%B8%B0%EB%B3%B8%20%EC%97%B0%EC%82%B0%20%5B%20Python%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B3%BC%20%EC%9D%B4%EB%AF%B8%EC%A7%80%20%EC%B2%98%EB%A6%AC%20%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# 행렬 더하기
#array1 = np.random.normal(0,1,(2,3))
array1 = np.random.randint(0,10, size=8).reshape(4,2)
print(array1)
print(array1*2)

In [10]:
#size가 다른 행렬들의 덧셈(broadcast)
array1 = np.arange(4).reshape(2,2)
print(array1)
array2 = np.arange(2).reshape(1,2)
print(array2)
print(np.add(array1,array2))
print("=============")
array3 = np.arange(4).reshape(2,2)
print(array3)
array4 = np.arange(2).reshape(2,1)
print(array4)
print(np.add(array3,array4))
print("=============")
# 행, 열 둘중에 하나라도 맞아야 덧셈이 가능함
#array5 = np.arange(9).reshape(3,3)
#print(array5)
#array6 = np.arange(2).reshape(2,1)
#print(array6)
#print(np.add(array5,array6))

[[0 1]
 [2 3]]
[[0 1]]
[[0 2]
 [2 4]]
[[0 1]
 [2 3]]
[[0]
 [1]]
[[0 1]
 [3 4]]


In [18]:
array1 = np.arange(9).reshape(3,3)
#print(array1)
array2 = np.arange(9).reshape(3,3)
#print(array2)
#행 붙이기
array3 = np.concatenate([array1,array2],axis = 0)
#print(array3)
#열 붙이기
array4 = np.concatenate([array1,array2],axis = 1)
#print(array4)
#print(array3)
print(array1)
print(np.add(array1,np.arange(3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
