<a href="https://colab.research.google.com/github/toot09/15012020_made/blob/master/Numpy%EC%9D%98%20%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# 단일 객체 저장 및 불러오기
array = np.arange(0,9)
np.save('saved.npy',array)

In [5]:
result  = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8]


In [10]:
# 복수 객체 저장 및 불러오기
array1 = np.random.randint(0,9,size=10).reshape(2,5)
array2 = np.random.randint(0,9,size=9).reshape(3,3)
print(array1)
print(array2)
np.savez('saved.npz',array1=array1,arrayTest=array2)

[[5 4 3 5 0]
 [5 5 4 5 8]]
[[5 7 8]
 [0 0 3]
 [8 4 5]]


In [18]:
# 복수객체 불러오기
data = np.load('saved.npz')
result1 = data['array1']
print(result1)
result2 = data['arrayTest']
print(result2)

[[5 4 3 5 0]
 [5 5 4 5 8]]
[[5 7 8]
 [0 0 3]
 [8 4 5]]


In [31]:
# numpy 원소 오름차순 정렬
array = np.array([5,1,7,12,5,9,123,3,1,7])
array.sort()
print(array)
print(array[::-1])
print(array[0:6])
print(array[6:0:-1])
print(array)

[  1   1   3   5   5   7   7   9  12 123]
[123  12   9   7   7   5   5   3   1   1]
[1 1 3 5 5 7]
[7 7 5 5 3 1]


TypeError: ignored

In [48]:
# 열기준 정렬
array1= np.array([[1,6,12,6],[3,6,21,1]])
# 행 기준 오름차순
#print(np.sort(array1, axis = 0))
array2= np.array([[1,6,12,6],[3,6,21,1],[2,1,6,0]])
# 열 기준 오름차순
print(np.sort(array2, axis = 1))
print(np.sort(array2))

array3 = np.array([6,2,6,1,3])
#print(np.sort(array3))
#print(np.sort(array3)[::-1])

[[ 1  6  6 12]
 [ 1  3  6 21]
 [ 0  1  2  6]]
[[ 1  6  6 12]
 [ 1  3  6 21]
 [ 0  1  2  6]]


In [52]:
#axis에 대한 행/렬 헷갈릴때 씀 (순서 : ㅣ-)
array2= np.array([[1,6,12,6],[3,6,21,1],[2,1,6,0]])
print(array2)
left, right = np.split(array2,[1],axis=1)
print(left)
print(right)
print(np.sum(array2,axis=1))


[[ 1  6 12  6]
 [ 3  6 21  1]
 [ 2  1  6  0]]
[[1]
 [3]
 [2]]
[[ 6 12  6]
 [ 6 21  1]
 [ 1  6  0]]
[25 31  9]
